name: Reactor
options:
  bundleIdPrefix: com.reactor
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.40"
settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    SWIFT_OBJC_BRIDGING_HEADER: Sources/Renderer/BridgingHeader.h
    MTL_HEADER_SEARCH_PATHS: Sources/Renderer
    METAL_HEADER_SEARCH_PATHS: Sources/Renderer
targets:
  Reactor:
    type: application
    platform: macOS
    sources:
      - path: Sources
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.reactor.app
        INFOPLIST_GENERATION_MODE: GeneratedFile
        PRODUCT_NAME: Reactor
        SWIFT_OBJC_BRIDGING_HEADER: Sources/Renderer/BridgingHeader.h
        GENERATE_INFOPLIST_FILE: "YES"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
    resources:
      - path: Resources
        type: group
